language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

# skip the install step for now
install: 
    - "pip install coveralls"
    - "pip install pyyaml"

script: coverage run -m tests.test

after_success: coveralls
